// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserIpTracker.Infrastructure.Data;

#nullable disable

namespace UserIpTracker.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20251215053211_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserIpTracker.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UserIpTracker.Domain.User", b =>
                {
                    b.OwnsOne("UserIpTracker.Domain.UserConnection", "LastConnection", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<IPAddress>("Ip")
                                .IsRequired()
                                .HasColumnType("inet")
                                .HasColumnName("last_ip");

                            b1.Property<DateTime?>("_lastSeenUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_seen_utc");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("UserIpTracker.Domain.UserConnection", "Connections", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<IPAddress>("Ip")
                                .IsRequired()
                                .HasColumnType("inet")
                                .HasColumnName("ip");

                            b1.Property<DateTime?>("_lastSeenUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_seen_utc");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("Ip");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Ip"), "spgist");

                            b1.HasIndex("user_id");

                            b1.ToTable("user_connections", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("Connections");

                    b.Navigation("LastConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
